-- Generated by SQL Maestro for MySQL. Release date 9/15/2008
-- 8/20/2015 9:16:38 AM
-- ----------------------------------
-- Alias: ezae at localhost
-- Database name: ezae
-- Host: localhost
-- Port number: 3306
-- User name: root
-- Server: 5.1.43-community
-- Session ID: 5
-- Character set: latin1
-- Collation: latin1_swedish_ci
-- Client encoding: utf8


SET FOREIGN_KEY_CHECKS=0;

CREATE DATABASE `ezae`
  CHARACTER SET `latin1`
  COLLATE `latin1_swedish_ci`;

USE `ezae`;

/* Tables */
CREATE TABLE `activities` (
  `seq`              bigint AUTO_INCREMENT NOT NULL,
  `moduleseq`        bigint,
  `userseq`          bigint,
  `iscompleted`      tinyint,
  `progress`         int,
  `dateofplay`       datetime,
  `learningplanseq`  bigint,
  `score`            int,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `adminmodules` (
  `seq`         bigint AUTO_INCREMENT NOT NULL,
  `companyseq`  bigint NOT NULL,
  `adminseq`    bigint NOT NULL,
  `moduleseq`   bigint NOT NULL,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `admins` (
  `seq`               bigint AUTO_INCREMENT NOT NULL,
  `name`              varchar(256),
  `username`          varchar(256),
  `password`          varchar(256),
  `emailid`           varchar(100),
  `mobileno`          varchar(20),
  `companyseq`        bigint,
  `createdon`         datetime,
  `isenabled`         tinyint,
  `issuper`           bit,
  `lastmodifiedon`    datetime NOT NULL,
  `signupformheader`  text,
  `ismanager`         tinyint,
  `parentadminseq`    bigint,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `companies` (
  `seq`            bigint AUTO_INCREMENT NOT NULL,
  `name`           varchar(256),
  `description`    varchar(500),
  `emailid`        varchar(100),
  `mobileno`       varchar(20),
  `contactperson`  varchar(100),
  `createdon`      datetime,
  `isenabled`      tinyint,
  `address`        varchar(200) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `phone`          varchar(20) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `prefix`         varchar(20),
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `companymodules` (
  `seq`         bigint AUTO_INCREMENT NOT NULL,
  `companyseq`  bigint NOT NULL,
  `adminseq`    bigint NOT NULL,
  `moduleseq`   bigint NOT NULL,
  `addedon`     datetime,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `leaderboard` (
  `seq`              bigint AUTO_INCREMENT NOT NULL,
  `name`             varchar(255) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `leaderboardtype`  varchar(50) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `learningplanseq`  bigint,
  `moduleseq`        bigint,
  `createdon`        datetime,
  `lastmodifiedon`   datetime,
  `isenabled`        tinyint,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `learningplanmodules` (
  `seq`                  bigint AUTO_INCREMENT NOT NULL,
  `learningplanseq`      bigint NOT NULL,
  `courseseq`            bigint NOT NULL,
  `isenableleaderboard`  tinyint,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `learningplanprofiles` (
  `seq`                 bigint AUTO_INCREMENT NOT NULL,
  `learningplanseq`     bigint NOT NULL,
  `learningprofileseq`  bigint NOT NULL,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `learningplans` (
  `seq`               bigint AUTO_INCREMENT NOT NULL,
  `adminseq`          bigint NOT NULL,
  `companyseq`        bigint NOT NULL,
  `title`             varchar(100) CHARACTER SET `utf8` COLLATE `utf8_general_ci` NOT NULL,
  `description`       varchar(250) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `isleaderboard`     tinyint,
  `issequencelocked`  tinyint,
  `isactive`          tinyint,
  `deactivateon`      datetime,
  `createdon`         datetime NOT NULL,
  `lastmodifiedon`    datetime NOT NULL,
  `activateon`        datetime,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `learningprofiles` (
  `seq`             bigint AUTO_INCREMENT NOT NULL,
  `tag`             varchar(50) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `adminseq`        bigint NOT NULL,
  `companyseq`      bigint NOT NULL,
  `createdon`       datetime NOT NULL,
  `description`     varchar(500) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `lastmodifiedon`  datetime NOT NULL,
  `awesomefontid`   varchar(100) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `mailmessage` (
  `seq`      bigint AUTO_INCREMENT NOT NULL,
  `name`     varchar(200),
  `subject`  varchar(200),
  `message`  text,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `mailmessageaction` (
  `seq`                bigint AUTO_INCREMENT NOT NULL,
  `messageid`          bigint,
  `sendondate`         datetime,
  `messagecondition`   varchar(45),
  `gettingmarksvalue`  int,
  `moduleseq`          bigint,
  `learningplanseq`    bigint,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `mailmessagelearningprofiles` (
  `seq`                bigint AUTO_INCREMENT NOT NULL,
  `messageid`          bigint,
  `learningprofileid`  bigint,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `mailmessagemails` (
  `seq`               bigint AUTO_INCREMENT NOT NULL,
  `messageactionseq`  bigint,
  `userseq`           bigint,
  `adminseq`          bigint,
  `failurecounter`    int,
  `failureerror`      varchar(1000),
  `savedon`           datetime,
  `senton`            datetime,
  `status`            varchar(20) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `sendon`            datetime,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `managercriteria` (
  `seq`            bigint AUTO_INCREMENT NOT NULL,
  `managerseq`     bigint NOT NULL,
  `criteriatype`   varchar(20) CHARACTER SET `utf8` COLLATE `utf8_general_ci` NOT NULL,
  `criteriavalue`  varchar(250) CHARACTER SET `utf8` COLLATE `utf8_general_ci` NOT NULL,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `managers` (
  `seq`             bigint AUTO_INCREMENT NOT NULL,
  `companyseq`      bigint NOT NULL,
  `adminseq`        bigint NOT NULL,
  `name`            varchar(250) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `email`           varchar(100) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `password`        varchar(250) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `isenabled`       tinyint,
  `createdon`       datetime,
  `lastmodifiedon`  datetime,
  `mobile`          varchar(20) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `matchingrules` (
  `seq`            bigint AUTO_INCREMENT NOT NULL,
  `usernamefield`  varchar(100) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `emailfield`     varchar(100) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `passwordfield`  varchar(100) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `adminseq`       bigint NOT NULL,
  `companyseq`     bigint NOT NULL,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `modules` (
  `seq`             bigint AUTO_INCREMENT NOT NULL,
  `title`           varchar(1000),
  `description`     varchar(2500) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `createdon`       datetime,
  `isenabled`       tinyint,
  `ispaid`          tinyint,
  `price`           double,
  `lastmodifiedon`  datetime NOT NULL,
  `maxscore`        double,
  `passpercent`     double,
  `companyseq`      bigint NOT NULL,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `my_log` (
  `timestamp`  varchar(32),
  `logger`     varchar(64),
  `level`      varchar(32),
  `message`    varchar(9999),
  `thread`     varchar(32),
  `file`       varchar(255),
  `line`       varchar(6)
) ENGINE = InnoDB;

CREATE TABLE `signupformfields` (
  `seq`             bigint AUTO_INCREMENT NOT NULL,
  `adminseq`        bigint NOT NULL,
  `companyseq`      bigint NOT NULL,
  `customfieldseq`  bigint NOT NULL,
  `isrequired`      tinyint,
  `isvisible`       tinyint,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `usercustomfields` (
  `seq`             bigint AUTO_INCREMENT NOT NULL,
  `companyseq`      bigint,
  `name`            varchar(256),
  `title`           varchar(256),
  `fieldtype`       varchar(20),
  `adminseq`        bigint NOT NULL,
  `lastmodifiedon`  datetime NOT NULL,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `userlearningprofiles` (
  `seq`       int AUTO_INCREMENT NOT NULL,
  `userseq`   bigint,
  `tagseq`    bigint NOT NULL,
  `adminseq`  bigint NOT NULL,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `users` (
  `seq`                bigint AUTO_INCREMENT NOT NULL,
  `username`           varchar(56),
  `password`           varchar(56) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `emailid`            varchar(150),
  `companyseq`         bigint,
  `customfieldvalues`  varchar(5000) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `createdon`          datetime,
  `isenabled`          tinyint,
  `adminseq`           bigint NOT NULL,
  `lastmodifiedon`     datetime NOT NULL,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

/* Indexes */
CREATE INDEX `foreign_activities_learningplan`
  ON `activities`
  (`learningplanseq`);

CREATE INDEX `foreign_key03`
  ON `activities`
  (`moduleseq`);

CREATE INDEX `foreign_key04`
  ON `activities`
  (`userseq`);

CREATE INDEX `foreign_adminmodule_admin`
  ON `adminmodules`
  (`adminseq`);

CREATE INDEX `foreign_adminmodule_company`
  ON `adminmodules`
  (`companyseq`);

CREATE INDEX `foreign_adminmodule_module`
  ON `adminmodules`
  (`moduleseq`);

CREATE INDEX `foreign_key02`
  ON `admins`
  (`companyseq`);

CREATE INDEX `foreign_leaderboard`
  ON `leaderboard`
  (`learningplanseq`);

CREATE INDEX `foreign_lp_admin`
  ON `learningplans`
  (`adminseq`);

CREATE INDEX `foreign_lp_company`
  ON `learningplans`
  (`companyseq`);

CREATE INDEX `foreign_tag_admin`
  ON `learningprofiles`
  (`adminseq`);

CREATE UNIQUE INDEX `unique_index`
  ON `learningprofiles`
  (`companyseq`, `awesomefontid`);

CREATE UNIQUE INDEX `unique_index`
  ON `mailmessageaction`
  (`messagecondition`, `moduleseq`, `learningplanseq`);

CREATE INDEX `foreign_managers_admin`
  ON `managers`
  (`adminseq`);

CREATE INDEX `foreign_managers_company`
  ON `managers`
  (`companyseq`);

CREATE INDEX `foreign_key01`
  ON `signupformfields`
  (`adminseq`);

CREATE INDEX `foreign_key02`
  ON `signupformfields`
  (`companyseq`);

CREATE INDEX `foreign_key03`
  ON `signupformfields`
  (`customfieldseq`);

CREATE INDEX `foreign_key06`
  ON `usercustomfields`
  (`companyseq`);

CREATE INDEX `foreign_uc_admin`
  ON `usercustomfields`
  (`adminseq`);

CREATE INDEX `foreign_ut_admin`
  ON `userlearningprofiles`
  (`adminseq`);

CREATE INDEX `foreign_ut_tag`
  ON `userlearningprofiles`
  (`tagseq`);

CREATE UNIQUE INDEX `unique_index`
  ON `userlearningprofiles`
  (`userseq`, `tagseq`);

CREATE INDEX `foreign_key01`
  ON `users`
  (`companyseq`);

CREATE INDEX `foreign_user_admin`
  ON `users`
  (`adminseq`);

CREATE UNIQUE INDEX `username`
  ON `users`
  (`username`);

/* Foreign Keys */
ALTER TABLE `activities`
  ADD CONSTRAINT `foreign_activities_learningplan`
  FOREIGN KEY (`learningplanseq`)
    REFERENCES `learningplans`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `activities`
  ADD CONSTRAINT `foreign_activities_user`
  FOREIGN KEY (`userseq`)
    REFERENCES `users`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `activities`
  ADD CONSTRAINT `foreign_actvities_module`
  FOREIGN KEY (`moduleseq`)
    REFERENCES `modules`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `adminmodules`
  ADD CONSTRAINT `foreign_adminmodule_admin`
  FOREIGN KEY (`adminseq`)
    REFERENCES `admins`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `adminmodules`
  ADD CONSTRAINT `foreign_adminmodule_company`
  FOREIGN KEY (`companyseq`)
    REFERENCES `companies`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `adminmodules`
  ADD CONSTRAINT `foreign_adminmodule_module`
  FOREIGN KEY (`moduleseq`)
    REFERENCES `modules`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `admins`
  ADD CONSTRAINT `foreign_admin_company`
  FOREIGN KEY (`companyseq`)
    REFERENCES `companies`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `learningplans`
  ADD CONSTRAINT `foreign_lp_admin`
  FOREIGN KEY (`adminseq`)
    REFERENCES `admins`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `learningplans`
  ADD CONSTRAINT `foreign_lp_company`
  FOREIGN KEY (`companyseq`)
    REFERENCES `companies`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `learningprofiles`
  ADD CONSTRAINT `foreign_tag_admin`
  FOREIGN KEY (`adminseq`)
    REFERENCES `admins`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `learningprofiles`
  ADD CONSTRAINT `foreign_tag_company`
  FOREIGN KEY (`companyseq`)
    REFERENCES `companies`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `managers`
  ADD CONSTRAINT `foreign_managers_admin`
  FOREIGN KEY (`adminseq`)
    REFERENCES `admins`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `managers`
  ADD CONSTRAINT `foreign_managers_company`
  FOREIGN KEY (`companyseq`)
    REFERENCES `companies`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `signupformfields`
  ADD CONSTRAINT `foreign_key01`
  FOREIGN KEY (`adminseq`)
    REFERENCES `admins`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `signupformfields`
  ADD CONSTRAINT `foreign_key02`
  FOREIGN KEY (`companyseq`)
    REFERENCES `companies`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `signupformfields`
  ADD CONSTRAINT `foreign_key03`
  FOREIGN KEY (`customfieldseq`)
    REFERENCES `usercustomfields`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `usercustomfields`
  ADD CONSTRAINT `foreign_uc_admin`
  FOREIGN KEY (`adminseq`)
    REFERENCES `admins`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `usercustomfields`
  ADD CONSTRAINT `foreign_uc_company`
  FOREIGN KEY (`companyseq`)
    REFERENCES `companies`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `userlearningprofiles`
  ADD CONSTRAINT `foreign_ut_admin`
  FOREIGN KEY (`adminseq`)
    REFERENCES `admins`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `userlearningprofiles`
  ADD CONSTRAINT `foreign_ut_tag`
  FOREIGN KEY (`tagseq`)
    REFERENCES `learningprofiles`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `users`
  ADD CONSTRAINT `foreign_user_admin`
  FOREIGN KEY (`adminseq`)
    REFERENCES `admins`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `users`
  ADD CONSTRAINT `foreign_user_company`
  FOREIGN KEY (`companyseq`)
    REFERENCES `companies`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;