-- Generated by SQL Maestro for MySQL. Release date 9/15/2008
-- 9/2/2014 3:18:35 PM
-- ----------------------------------
-- Alias: test at localhost
-- Database name: test
-- Host: localhost
-- Port number: 3306
-- User name: root
-- Server: 5.0.51a-community-nt
-- Session ID: 4
-- Character set: latin1
-- Collation: latin1_swedish_ci
-- Client encoding: utf8


SET FOREIGN_KEY_CHECKS=0;



/* Tables */
CREATE TABLE `activity` (
  `seq`          bigint AUTO_INCREMENT NOT NULL,
  `moduleseq`    bigint,
  `userseq`      bigint,
  `dateofplay`   datetime,
  `iscompleted`  tinyint,
  `progress`     int,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `admins` (
  `seq`             bigint AUTO_INCREMENT NOT NULL,
  `name`            varchar(256),
  `username`        varchar(256),
  `password`        varchar(256),
  `dateofcreation`  datetime,
  `enabled`         tinyint,
  `emailid`         varchar(256),
  `mobileno`        varchar(20),
  `companyseq`      bigint,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `company` (
  `seq`             bigint AUTO_INCREMENT NOT NULL,
  `name`            varchar(256),
  `description`     varchar(256),
  `dateofcreation`  datetime,
  `enabled`         tinyint,
  `emailid`         varchar(256),
  `mobileno`        varchar(20),
  `contactperson`   varchar(256),
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `modules` (
  `seq`             bigint AUTO_INCREMENT NOT NULL,
  `companyseq`      bigint,
  `dateofcreation`  datetime,
  `dateofexpiry`    datetime,
  `title`           varchar(1000),
  `description`     varchar(2500) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `uploadedby`      varchar(256),
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `user` (
  `seq`                bigint AUTO_INCREMENT NOT NULL,
  `username`           varchar(56),
  `password`           varchar(56) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `emailid`            varchar(150),
  `companyseq`         bigint,
  `customfieldvalues`  varchar(5000) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

CREATE TABLE `usercustomfields` (
  `seq`          bigint AUTO_INCREMENT NOT NULL,
  `companyseq`   bigint,
  `name`         varchar(256),
  `title`        varchar(256),
  `description`  varchar(500),
  `type`         varchar(20),
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB;

/* Indexes */
CREATE INDEX `foreign_key03`
  ON `activity`
  (`moduleseq`);

CREATE INDEX `foreign_key04`
  ON `activity`
  (`userseq`);

CREATE INDEX `foreign_key02`
  ON `admins`
  (`companyseq`);

CREATE INDEX `foreign_key05`
  ON `modules`
  (`companyseq`);

CREATE INDEX `foreign_key01`
  ON `user`
  (`companyseq`);

CREATE INDEX `username`
  ON `user`
  (`username`);

CREATE INDEX `foreign_key06`
  ON `usercustomfields`
  (`companyseq`);

/* Foreign Keys */
ALTER TABLE `activity`
  ADD CONSTRAINT `foreign_key03`
  FOREIGN KEY (`moduleseq`)
    REFERENCES `modules`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `activity`
  ADD CONSTRAINT `foreign_key04`
  FOREIGN KEY (`userseq`)
    REFERENCES `user`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `admins`
  ADD CONSTRAINT `foreign_key02`
  FOREIGN KEY (`companyseq`)
    REFERENCES `company`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `modules`
  ADD CONSTRAINT `foreign_key05`
  FOREIGN KEY (`companyseq`)
    REFERENCES `company`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `user`
  ADD CONSTRAINT `foreign_key01`
  FOREIGN KEY (`companyseq`)
    REFERENCES `company`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;

ALTER TABLE `usercustomfields`
  ADD CONSTRAINT `foreign_key06`
  FOREIGN KEY (`companyseq`)
    REFERENCES `company`(`seq`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION;


