<?php


  $ConstantsArray = array('dbServerUrl' => 'G:\\Webdocs\\EZAsessmentEngine\\httpdocs\\'
    ,'imagefolderpath' => 'G:\\Webdocs\\EZAsessmentEngine\\httpdocs\\images\\'
    ,'docspath' => 'G:\\Webdocs\\EZAsessmentEngine\\httpdocs\\docs\\'
    ,'ImagePath' => 'G:\\Webdocs\\EZAsessmentEngine\\httpdocs\\Images\\AdminImages\\'
    ,'UserImagePath' => 'G:\\Webdocs\\EZAsessmentEngine\\httpdocs\\Images\\UserImages\\');
  $ConstantsArray['ApplicationURL'] = "http://localhost:8080";

  $ConstantsArray["CUSTOM_FIELD_PREFIX"]  = "cus_";
  //$ConstantsArray = array('dbServerUrl' => '/home/satyain/public_html/giftcard/');
  //Logger::configure($ConstantsArray['dbServerUrl'] .'log4php/log4php.xml');
  $ConstantsArray['ApplicationURL'] = "http://localhost:8083/httpdocs";
  $Log4PHP_MyDBLogger = "myDBLogger";
  $Log4PHP_MyMailerLogger = "myMailerLogger";
  $Log4PHP_MyFileLogger = "myFileLogger";

  $CUSTOM_FIELD_PREFIX = "cus_"

?>