<?php

  $ConstantsArray = array('dbServerUrl' => 'G:\\Webdocs\\EZAsessmentEngine\\httpdocs\\','ImagePath' => 'D:\\projects\\ezae\\httpdocs\\Images\\AdminImages\\','UserImagePath' => 'D:\\projects\\ezae\\httpdocs\\Images\\UserImages\\');
  $ConstantsArray['ApplicationURL'] = "http://localhost:8080";
  $ConstantsArray["CUSTOM_FIELD_PREFIX"]  = "cus_";
  //$ConstantsArray = array('dbServerUrl' => '/home/satyain/public_html/giftcard/');
  //Logger::configure($ConstantsArray['dbServerUrl'] .'log4php/log4php.xml');

  $Log4PHP_MyDBLogger = "myDBLogger";
  $Log4PHP_MyMailerLogger = "myMailerLogger";
  $Log4PHP_MyFileLogger = "myFileLogger";

  $CUSTOM_FIELD_PREFIX = "cus_"


?>