<?php

  
  $ConstantsArray = array('dbServerUrl' => 'D:\\projects\\ezae\\httpdocs\\','imagefolderpath' => 'D:\\projects\\ezae\\httpdocs\\images\\','docspath' => 'D:\\projects\\ezae\\httpdocs\\docs\\','ImagePath' => 'D:\\projects\\ezae\\httpdocs\\Images\\AdminImages\\','UserImagePath' => 'D:\\projects\\ezae\\httpdocs\\Images\\UserImages\\');
  $ConstantsArray['ApplicationURL'] = "http://localhost:8080";

  $ConstantsArray["CUSTOM_FIELD_PREFIX"]  = "cus_";
  //$ConstantsArray = array('dbServerUrl' => '/home/satyain/public_html/giftcard/');
  //Logger::configure($ConstantsArray['dbServerUrl'] .'log4php/log4php.xml');  
  $ConstantsArray['ApplicationURL'] = "http://localhost:8083/httpdocs";
  $Log4PHP_MyDBLogger = "myDBLogger";
  $Log4PHP_MyMailerLogger = "myMailerLogger";
  $Log4PHP_MyFileLogger = "myFileLogger";
  
  $CUSTOM_FIELD_PREFIX = "cus_"

?>